### ISSUE TITLE
Add filtering demo

### ISSUE THREAD

**Issue by voytek** [voytekresearch/spr#13]
We need to split the 00_dsp_and_sims.ipynb into a few separate notebooks. One of those new ones need to include a filtering demo, showing how filtering affects the sharp temporal features of simulated and real nonsinusoidal oscillations.

**Comment by voytek** [comment]
@sydney-smith reminded me that we can pull from some of the materials on the /tutorials dev branch like these ones:

- https://github.com/voytekresearch/Tutorials/blob/dev/01-ElectrophysiologicalTimeSeries.ipynb
- https://github.com/voytekresearch/Tutorials/blob/dev/02-Filtering.ipynb

**Comment by QuirinevEngen** [comment]
I added a new notebook to discuss basic filtering and an example with a sawtooth filter. Is there anything else we can add to these first sections of the workshop?

**Comment by voytek** [comment]
Great work, I'm closing this one out.
