### ISSUE TITLE
Add bycycle burst detection settings demo

### ISSUE THREAD

**Issue by voytek** [voytekresearch/spr#15]
We need to add a demo showing how things like monotonicity fraction work.

For example, show a pure sinusoid, triangle wave, sawtooth, etc. and how the derivative for all points between every peak and trough will be positive (or negative), giving a monotonicity fraction of 100%. And how once some noise is added to those, the proportion of the derivative that all goes in the same direction (positive or negative) will be lower.

**Comment by voytek** [comment]
@ryanhammonds this would be a good place to show some of the stuff you and Kenton have been working on, too

**Comment by ryanhammonds** [comment]
@voytek added a demo here: https://github.com/voytekresearch/spr/blob/master/tutorials/02_bycycle/bycycle_03-BurstDetection.ipynb

This image sums up why tuning with dual amp threshold is easier - it's less sensitive and doesn't require as precise of tuning like the bycycle method.

<img width="714" alt="Screenshot 2023-09-13 at 4 54 21 PM" src="https://github.com/voytekresearch/spr/assets/34786005/5a593714-1679-484b-96e8-401443d05484">

**Comment by voytek** [comment]
Nice! A few stray comments:

"Note that the " just... ends?

Also, when I run the last cell to plot the grid search results, I get the following?

`AttributeError: 'Figure' object has no property 'width_ratios'`

**Comment by voytek** [comment]
Ah, I was on 3.5.1. It works after upgrading to 3.7.x. Just note that it definitely _doesn't_ work in 3.5.x (or less, probably). In case it comes up during the session.
