### ISSUE TITLE
Add more nonsinusoidal demos

### ISSUE THREAD

**Issue by voytek** [voytekresearch/spr#17]
Update the below tutorial and fold it into the bycycle tutorials:

https://github.com/voytekresearch/Tutorials/blob/dev/08-FrequencyMisinterpretations.ipynb

**Comment by sydney-smith** [comment]
Added a demo to bycycle 00-introduction illustrating the relationship between nonsinusoidal signals and harmonics, especially in the context of filtering.

**Comment by voytek** [comment]
This is a great addition, Sydney!
