### ISSUE TITLE
Add band ratios demo

### ISSUE THREAD

**Issue by voytek** [voytekresearch/spr#18]
From here:

https://github.com/voytekresearch/Tutorials/blob/dev/07-CommonMisinterpretations.ipynb
https://github.com/voytekresearch/Tutorials/blob/dev/08-FrequencyMisinterpretations.ipynb

But then point to Tom's paper and all his lovely materials here:

https://github.com/voytekresearch/BandRatios/tree/main/notebooks

**Comment by TomDonoghue** [comment]
There's a tutorial that describes band-ratio issues (leading into the paper) here:
https://fooof-tools.github.io/fooof/auto_motivations/measurements/plot_BandRatios.html

**Comment by voytek** [comment]
@mwprestonjr grab some of the materials from the links above and fold them in as appropriate

**Comment by mwprestonjr** [comment]
I adapted the tutorial that Tom linked to create the DSP and Simulations - Band Ratios notebook. I also used the tutorials linked above to expand the DSP and Simulations - Introduction notebook.

**Comment by voytek** [comment]
One quick thing before we close this out:
* "This tutorial was adapted for SPR 2023 by Michael Preston. The original can be found here."
* Change this to "This tutorial was adapted for SPR 2023 by Michael Preston from materials written by Tom Donoghue from Dononghue et al., _eNeuro_ 2020 [LINK]. The original can be found here".

**Comment by mwprestonjr** [comment]
Done!
